name: Haskell CI


on: [push]
name: build
jobs:
  runhaskell:
    name: Main
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '9.2.7' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defalts to 'latest'
          enable-stack: true
          stack-version: '2.9.3'
      - run: runhaskell app/Main.hs
      
      
      
